### ISSUE TITLE
Todo list for 1.x

### ISSUE THREAD

**Issue by bergos** [rdf-ext/discussions#23]
- [ ] implement [RDFJS Representation Task Force spec](https://github.com/rdfjs/representation-task-force)
  - [x] [core](https://github.com/rdf-ext/rdf-ext/tree/develop) (Terms, Quads, Graphs)
    - [x] [Data Model](https://github.com/rdf-ext/rdf-data-model/tree/develop)
    - [x] [Dataset](https://github.com/rdf-ext/rdf-dataset-simple/tree/develop)
    - [x] Stream Interfaces, ([Source](https://github.com/rdf-ext/rdf-source/tree/develop), [FilterStream](https://github.com/rdf-ext/rdf-filter-stream/tree/develop))
  - [ ] parsers
    - [x] [JSON-LD](https://github.com/rdf-ext/rdf-parser-jsonld/tree/develop)
    - [x] [Turtle/N-Triples](https://github.com/rdf-ext/rdf-parser-n3/tree/develop)
    - [ ] RDF/XML
  - [ ] serializers
    - [x] JSON-LD
    - [ ] Turtle
    - [x] N-Triples
  - [x] stores
    - [x] rename LdpStore to WebStore and use rdf-fetch
    - [x] SPARQL
    - [x] Dataset (replaces in memory store)
  - [ ] formats
    - [x] common formats
    - [ ] html formats
  - [ ] others
    - [x] rdf-fetch
    - [ ] clownface
    - [ ] simplerdf
      - [ ] simplerdf-fetch
      - [ ] hydra-fetch
- [x] replace request with [fetch](https://fetch.spec.whatwg.org/) (incl. polyfill)

Optional:
- [ ] implement indexed dataset
- [ ] port LDF query engine to RDFJS interfaces

**Comment by elf-pavlik** [comment]
> replace request with fetch (incl. polyfill)

for polyfill do you plan to use:
- https://github.com/github/fetch (browser)
- https://github.com/bitinn/node-fetch (node.js)
